version: '3.9'
services:
  db:
    image: postgres
    restart: always
    ports:
     - ${DB_PORT:-5432}:5432
    volumes:
     - ./database/script/kaggle.ddl.sql:/docker-entrypoint-initdb.d/1-ddl.sql
     - ./database/data:/docker-entrypoint-initdb.d/data
     - ./database/script/import.sh:/docker-entrypoint-initdb.d/2-import.sh
     - ./database/script/cleanup.sql:/docker-entrypoint-initdb.d/3-cleanup.sql
    environment:
     - POSTGRES_PASSWORD=neebai9izooHio4athie6ahj0haiph
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
     - ${BACKEND_PORT:-7000}:7000
    depends_on:
     - db
    environment:
     - KETI_DB_PORT=5432
     - KETI_DB_HOST=db