version: '3.9'
services:
  db:
    container_name: kaggle-keti
    image: postgres
    restart: always
    ports:
     - ${DB_PORT:-5432}:5432
    volumes:
     - ./script/kaggle.ddl.sql:/docker-entrypoint-initdb.d/1-ddl.sql
     - ./data:/docker-entrypoint-initdb.d/data
     - ./script/import.sh:/docker-entrypoint-initdb.d/2-import.sh
     - ./script/cleanup.sql:/docker-entrypoint-initdb.d/3-cleanup.sql
    environment:
     POSTGRES_PASSWORD: neebai9izooHio4athie6ahj0haiph
